### ISSUE TITLE
Receiving a message from the space-shooter plugin crashes the AngularTest plugin

### ISSUE THREAD

**Issue by LucasVandroux** [oVirt/samples-uiplugins#1]
## Summary
Receiving a message from the space-shooter plugin crashes the AngularTest plugin.

### Setup Configuration
1. Install the [space-shooter](https://github.com/oVirt/samples-uiplugins/tree/master/space-shooter-plugin) plugin by following the installation guidelines in the `README` file. Edit the `space-shooter.json` file directly.

2. Install the [AngularTest](https://github.com/oVirt/samples-uiplugins/tree/master/angular-demo-plugin) plugin by following the guidelines in the `README`. Change the  `allowedMessageOrigins` option in the `plugin.js` file with the same url as in the `space-shooter.json` file.

### Steps to Reproduce
1. Just after logging in the `Admin Panel`, open the `Data Centers` tab.
2. Right click on the first datacenter and select `Protect DataCenter from Alien Invasion`. 

### Actual Results
The `MessageReceived` function of the AngularTest plugin throw an exception and it crashes.

Here is the log in the console :
```
Fri Oct 10 11:26:35 GMT+800 2014 org.ovirt.engine.ui.webadmin.plugin.PluginManager
INFO: Invoking event handler function [MessageReceived] for plugin [AngularTest] 

Fri Oct 10 11:26:35 GMT+800 2014 org.ovirt.engine.ui.webadmin.plugin.PluginManager
SEVERE: Exception caught while invoking event handler function [MessageReceived] for plugin [AngularTest]: SyntaxError: Unexpected token G

Fri Oct 10 11:26:35 GMT+800 2014 org.ovirt.engine.ui.webadmin.plugin.PluginManager
WARNING: Plugin [AngularTest] removed from service due to failure 
```

### Expected Results
The `MessageReceived` function should parse the JSON, find out it is not the recipient and move on.

### Configuration 
Server OS: CentOS release 6.5 (Final)
Engine: ovirt-engine 3.5

**Comment by david-caro** [comment]
If this is still an issue, please open a bug on http://bugzilla.redhat.com or create a patch at http://gerrit.ovirt.org thanks
